name: First Git Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build and test with Cobertura
        run: |
          ./gradlew clean build cobertura
      - name: Upload Cobertura report
        uses: actions/upload-artifact@v2
        with:
          name: cobertura-report
          path: build/reports/cobertura/xml/