name: First Git Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and run tests with JaCoCo
        run: ./gradlew clean build jacocoTestReport --stacktrace

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/test-results/test

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/reports/coverage/report.csv

      - name: Print CSV values as a comment in PR
        run: |
          COMMENT="Hello World!"
          PR_NUMBER=$(echo "$GITHUB_REF" | awk 'BEGIN { FS="/" } { print $3 }')
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments"
          curl --request POST --url "$URL" --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --header "content-type: application/json" --data "{\"body\": \"$COMMENT\"}"