name: First Git Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and run tests with JaCoCo
        run: ./gradlew clean build jacocoTestReport --stacktrace

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/test-results/test

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html/index.html

      - name: Display code coverage in console
        run: |
            cat build/reports/jacoco/test/html/index.html | grep Total